audio_play_sound(snd_break2, 20, 0)
audio_sound_gain(snd_break2, global.SOUND_VOLUME, 0)
shard = instance_create_depth(x, y, -100, obj_heartshard)
shard.image_speed = random_range(0.8, 1.3)
shard.vspeed = random_range(-5, 5)
shard.hspeed = random_range(-5, 5)
shard.gravity = 0.2 * (30 / room_speed)
shard2 = instance_create_depth(x, y, -100, obj_heartshard)
shard2.image_speed = random_range(0.8, 1.3)
shard2.vspeed = random_range(-5, 5)
shard2.hspeed = random_range(-5, 5)
shard2.gravity = 0.2 * (30 / room_speed)
shard3 = instance_create_depth(x, y, -100, obj_heartshard)
shard3.image_speed = random_range(0.8, 1.3)
shard3.vspeed = random_range(-5, 5)
shard3.hspeed = random_range(-5, 5)
shard3.gravity = 0.2 * (30 / room_speed)
shard4 = instance_create_depth(x, y, -100, obj_heartshard)
shard4.image_speed = random_range(0.8, 1.3)
shard4.vspeed = random_range(-5, 5)
shard4.hspeed = random_range(-5, 5)
shard4.gravity = 0.2 * (30 / room_speed)
shard5 = instance_create_depth(x, y, -100, obj_heartshard)
shard5.image_speed = random_range(0.8, 1.3)
shard5.vspeed = random_range(-5, 5)
shard5.hspeed = random_range(-5, 5)
shard5.gravity = 0.2 * (30 / room_speed)
shard6 = instance_create_depth(x, y, -100, obj_heartshard)
shard6.image_speed = random_range(0.8, 1.3)
shard6.vspeed = random_range(-5, 5)
shard6.hspeed = random_range(-5, 5)
shard6.gravity = 0.2 * (30 / room_speed)
instance_destroy()
