global.classicmode = 0
global.menu = 0
global.hp = 99
global.glasssoul = 0
global.name = ""
global.deaths = 0
global.charadeath = 0
global.px = 0
global.fpsmode = 0
global.py = 0
global.wave = 0
global.wasanidiot = 0
global.lunaticmode = 0
global.survival = 0
global.debug = 0
global.MASTER_VOLUME = 1
global.SOUND_VOLUME = 1
global.MUSIC_VOLUME = 1
global.bosshp = 0
global.bossmaxhp = 0
global.lunaticsouls = 0
global.asgorepissed = 0
global.damagetaken = 0
global.hphealed = 0
global.cheatingpieceofshitgofuckyourself = 0
ini_open("undertale.ini")
if ini_section_exists("General")
{
    global.name = ini_read_string("General", "A", "")
    global.deaths = ini_read_real("General", "B", 0)
    global.wasanidiot = ini_read_real("General", "D", 0)
    global.SOUND_VOLUME = ini_read_real("General", "H", 1)
    global.MUSIC_VOLUME = ini_read_real("General", "G", 1)
    global.MASTER_VOLUME = ini_read_real("General", "F", 1)
}
if (global.wasanidiot && ini_read_real("General", "E", 0) < 3)
{
	ini_write_real("General", "D", 0)
	audio_stop_sound(mus_story)
	room_goto(room_credits)
}
ini_close()
instance_create_depth(5, 5, -1000000, obj_quit)
global.text_data = ds_map_create()
ds_map_add(global.text_data, "KEY_INTRO_0", "Long ago, two races&ruled over Earth:&HUMANS and MONSTERS./")
ds_map_add(global.text_data, "KEY_INTRO_1", "One day, war broke&out between the two&races./")
ds_map_add(global.text_data, "KEY_INTRO_2", "After a long battle,&the humans were&victorious./")
ds_map_add(global.text_data, "KEY_INTRO_3", "As well as they should&be, they HATE monsters./")
ds_map_add(global.text_data, "KEY_INTRO_4", "Because after all.../")
ds_map_add(global.text_data, "KEY_INTRO_5", "We're not done yet./")
ds_map_add(global.text_data, "KEY_INTRO_6", "Come on, human. Don't&you remember?/")
ds_map_add(global.text_data, "KEY_INTRO_7", "We have one last job&to do, partner./")
ds_map_add(global.text_data, "KEY_INTRO_8", "Let's take out the KING./")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_0", "So./")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_0-1", "You came back./")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_0-2", "Why did you act like such\nan idiot last time?/")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_0-3", ".../")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_0-4", "Don't bother answering./")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_0-5", "Let's just do this thing./%%")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_1", "Are you serious?/")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_1-1", "You did it again!/")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_1-2", "Just follow my orders, please?/")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_1-3", "It will make our lives\na lot easier./%%")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_2", ".../")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_2-1", "At this point, I don't\ncare./")
ds_map_add(global.text_data, "KEY_INTRO_POSTSUICIDE_2-2", "Do whatever the hell\nyou want!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_0", "Curious...&I've never seen a flower...&Cry before.../")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_0-1", "I wonder why it ran away...&Did a monster try to hurt them?/%%")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_1", "Oh./")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_1-1", "You must be the human that&flower was talking about.../")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_1-2", "It seemed afraid of you.../%%")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_2", "Are you... a MONSTER?&Are you willing... to FIGHT?/")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_2-1", ".../%%")
ds_map_add(global.text_data, "KEY_ASGORE_TALK_3", "Let's get this over with.&Join me at the barrier&this instant./%%")
ds_map_add(global.text_data, "KEY_GAMEOVER_0", "You cannot give up&just yet.../")
ds_map_add(global.text_data, "KEY_GAMEOVER_0-1", "!&Stay determined.../%%")
ds_map_add(global.text_data, "KEY_GAMEOVER_1", "Don't lose hope!/")
ds_map_add(global.text_data, "KEY_GAMEOVER_1-1", "!&Stay determined.../%%")
ds_map_add(global.text_data, "KEY_GAMEOVER_2", "It cannot end&now!/")
ds_map_add(global.text_data, "KEY_GAMEOVER_2-1", "!&Stay determined.../%%")
ds_map_add(global.text_data, "KEY_GAMEOVER_3", "You are going to&be alright.../")
ds_map_add(global.text_data, "KEY_GAMEOVER_3-1", "!&Stay determined.../%%")
ds_map_add(global.text_data, "KEY_GAMEOVER_4", "Our fate rests&upon you.../")
ds_map_add(global.text_data, "KEY_GAMEOVER_4-1", "!&Stay determined.../%%")
ds_map_add(global.text_data, "KEY_GAMEOVERSUICIDE_0", "/RYou freaking idiot!/")
ds_map_add(global.text_data, "KEY_GAMEOVERSUICIDE_0-1", "/RWhy did you do that?/")
ds_map_add(global.text_data, "KEY_GAMEOVERSUICIDE_0-2", "/RMaybe next time, I'll just&kill him myself./")
ds_map_add(global.text_data, "KEY_GAMEOVERSUICIDE_0-3", "/RYou are WORTHLESS.&Don't bother coming back./%%")
ds_map_add(global.text_data, "KEY_GAMEOVERCHEATED_0", "that expression.../")
ds_map_add(global.text_data, "KEY_GAMEOVERCHEATED_0-1", "that's the expression of&someone who tried to cheat.../")
ds_map_add(global.text_data, "KEY_GAMEOVERCHEATED_0-2", "did you really think you&would get away with it?/")
ds_map_add(global.text_data, "KEY_GAMEOVERCHEATED_0-3", "you dirty hacker./%%")
ds_map_add(global.text_data, "KEY_ASGORE_INTRO", "* (A strange light fills the&  room.)/")
ds_map_add(global.text_data, "KEY_ASGORE_INTRO-1", "* (Twilight is shining through&  the barrier.)/")
ds_map_add(global.text_data, "KEY_ASGORE_INTRO-2", "* (Dust floats throughout the&  underground.)/")
ds_map_add(global.text_data, "KEY_ASGORE_INTRO-3", "* (ASGORE stands between you&  and the absolute.)/")
ds_map_add(global.text_data, "KEY_ASGORE_INTRO-4", "* (It seems as if your journey&  is coming to an end.)/")
ds_map_add(global.text_data, "KEY_ASGORE_INTRO-5", "    * (You're filled with&        DETERMINATION.)/")
ds_map_add(global.text_data, "KEY_ASGORE_INTROTALK_0", "Human... No...&Whatever you are.../")
ds_map_add(global.text_data, "KEY_ASGORE_INTROTALK_0-1", "It is time.../%%")
ds_map_add(global.text_data, "KEY_ASGORE_INTROTALK_1", "Goodbye./%%")
ds_map_add(global.text_data, "KEY_ASGORE_IDLE_0", "* Asgore attacks!/?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLE_1", "/R* DETERMINATION./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLE_2", "/R* In my absolute way./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLE_3", "/R* =)/?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLE_4", "/R* ASGORE./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLE_5", "/R* Get it over with./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLELUNATIC_0", "* Asgore attacks!/?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLELUNATIC_1", "/R* We have a long way to\n  go, partner./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLELUNATIC_2", "/R* I have no words for this./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLELUNATIC_3", "/R* The souls are rebelling./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLELUNATIC_4", "/R* We are in trouble./?")
ds_map_add(global.text_data, "KEY_ASGORE_IDLELUNATIC_5", "/R* Just finish the job./?")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_1", "* You tell Asgore that he has&  killed you before./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_1-1", "* He chuckles./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_2", "* You tell Asgore that he has&  killed you twice before./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_2-1", "* He smiles./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_3", "* You tell Asgore that he has&  killed you three times before./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_3-1", "* He nods with a menacing grin./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_4", "* You tell Asgore that he has&  killed you four times before./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_4-1", "* He doesn't care./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_5", "* You tell Asgore that he has&  killed you five times before./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_5-1", "* He points his trident at you&  in a threatening manner./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_6", "* You tell Asgore that he has&  killed you many times./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_6-1", "* He points his trident at you&  in a threatening manner.&  He seems eager./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_7", "* You tell Asgore that he has&  killed you too many times to&  count./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_DEATH_7-1", "* He points his trident at you&  in a threatening manner.&  He wants to carry on with it./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_0", "* You loudly tell Asgore that you&  killed everyone he loves./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_0-1", "* Nothing happened./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_1", "* You tell Asgore that you want&  to kill him./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_1-1", "* He smiles./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_2", "* You firmly tell Asgore to give&  up./")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_2-1", "* He doesn't care./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_3", "* Seems talking won't do any&  more good./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_4", "/R* Just finish the job.&  That's the least we can do./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_5", "/R* What are you doing?&  Just finish him!/W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_ACT_6", "/R* Alright, I'll do it myself./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_BUTTONASSEMBLY_0", "/R* I look around for pieces&  of the button./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_BUTTONASSEMBLY_1", "/R* I pick up a piece of the&  button./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_BUTTONASSEMBLY_2", "/R* I pick up another piece&  of the button./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_BUTTONASSEMBLY_3", "/R* I pick up remaining pieces./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_BUTTONASSEMBLY_4", "/R* DETERMINATION./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_BUTTONASSEMBLY_5", "* But the button was already&  assembled./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_0", "* You stare at Asgore./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_0-1", "* Amidst the shining light, you\n  remember something./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_0-2", "* Asgore didn't have integrity\n  during the war./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_0-3", "* Knowing this, you steal the\n  Integrity Soul.\n* Asgore's DEFENSE dropped!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_1", "* You stare at Asgore./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_1-1", "* Amidst the shining light, you\n  remember something./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_1-2", "* Monsters persevered thanks to\n  this worthless creature, despite\n  the will to harness your power./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_1-3", "* In anger, you steal the\n  Perseverance Soul.\n* Asgore's DEFENSE dropped!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_2", "* You stare at Asgore./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_2-1", "* Amidst the shining light, you\n  remember something./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_2-2", "* Monsters were brave enough to\n  try and stop you./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_2-3", "* While they all fell, Asgore\n  isn't showing any signs of\n  giving up./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_2-4", "* To lower his chances of winning,\n  you steal the Bravery Soul.\n* Asgore's DEFENSE dropped!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_3", "* You stare at Asgore./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_3-1", "* Amidst the shining light, you\n  remember something./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_3-2", "* Monsters would done justice to\n  Asgore if they had the will./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_3-3", "* But you, as a human, want it.\n  You steal the Justice Soul.\n* Asgore's DEFENSE dropped!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_4", "* You stare at Asgore./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_4-1", "* Amidst the shining light, you\n  remember something./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_4-2", "* There is no kindness on either\n  side of these forces./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_4-3", "* You steal the Kindness Soul.\n* Asgore's DEFENSE dropped!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_5", "* You stare at Asgore./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_5-1", "* Amidst the shining light, you\n  remember something./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_5-2", "* Now all that is left is the\n  persistence to keep going.\n  No matter what./")
ds_map_add(global.text_data, "KEY_ASGORE_LUNATICSOUL_5-3", "* You steal the Patience Soul.\n* Asgore's DEFENSE dropped to 0!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_CHECK_NOPIE", "* ASGORE - 205 ATK 255 DEF&  Our last target.&  Complete the mission./%%")
ds_map_add(global.text_data, "KEY_ASGORE_CHECK_NOPIE_INFDEF", "* ASGORE - 205 ATK INF DEF&  Our last target.&  Complete the mission./%%")
ds_map_add(global.text_data, "KEY_ASGORE_CHECK_NOPIE_NODEF", "* ASGORE - 205 ATK 0 DEF&  Our last target.&  Complete the mission./%%")
ds_map_add(global.text_data, "KEY_ASGORE_CHECK_PIE", "* ASGORE - 255 ATK 255 DEF&  You pissed him off.&  Just get this over with./%%")
ds_map_add(global.text_data, "KEY_ASGORE_CHECK_PIE_INFDEF", "* ASGORE - 255 ATK INF DEF&  You pissed him off.&  Just get this over with./%%")
ds_map_add(global.text_data, "KEY_ASGORE_CHECK_PIE_NODEF", "* ASGORE - 255 ATK 0 DEF&  You pissed him off.&  Just get this over with./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_0", "* You ate the Butterscotch Pie.&  Your HP was maxed out./")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_0-1", "* The smell reminded Asgore of&  what he is fighting for.../")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_0-2", "* Asgore's ATTACK increased!/%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_1", "/R* DETERMINATION./W/%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_1_0", "* But there was no more LOVE./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_1_1", "* I get it, you wish you had&  more LOVE. But you used it all./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_1_2", "* You should stop right now. OK?&  You won't like what happens./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_1_3", "/R* This is your final warning./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_1_4", "/R* Don't say I didn't warn you./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_1_5", "/R* Determination.../%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_2", "* You ate the Snowman Piece.&  You recovered 45 HP./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_2_MAX", "* You ate the Snowman Piece.&  Your HP was maxed out./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_3", "* You ate the Legendary Hero.&  ATK increased by 4.&  You recovered 40 HP./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_3_MAX", "* You ate the Legendary Hero.&  ATK increased by 4.&  Your HP was maxed out./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_4", "* You ate the Face Steak.&  You recovered 60 HP./%%")
ds_map_add(global.text_data, "KEY_ASGORE_ITEM_4_MAX", "* You ate the Face Steak.&  Your HP was maxed out./%%")
ds_map_add(global.text_data, "KEY_FIGHTMENU", "* Asgore")
ds_map_add(global.text_data, "KEY_ACTMENU", "* Check         * Talk\n* FIGHT         * ITEM")
ds_map_add(global.text_data, "KEY_ACTMENULUNATIC", "* Check         * Talk\n* FIGHT         * ITEM\n* Steal")
ds_map_add(global.text_data, "KEY_PRECREDITS_0", "We did it, partner./")
ds_map_add(global.text_data, "KEY_PRECREDITS_0-1", "We eradicated everyone.&Every last monster./")
ds_map_add(global.text_data, "KEY_PRECREDITS_0-2", "However, there is one more&target that needs to be&annihilated./")
ds_map_add(global.text_data, "KEY_PRECREDITS_0-3", "But we'll settle this score&some other time./")
ds_map_add(global.text_data, "KEY_PRECREDITS_0-4", "For now, enjoy being here,&in the darkness./")
ds_map_add(global.text_data, "KEY_PRECREDITS_0-5", "Alone./%%")
ds_map_add(global.text_data, "KEY_PRECREDITSCHARA_0", "You're so stupid./")
ds_map_add(global.text_data, "KEY_PRECREDITSCHARA_0-1", "We came all this way.../")
ds_map_add(global.text_data, "KEY_PRECREDITSCHARA_0-2", "And you do NOTHING?/")
ds_map_add(global.text_data, "KEY_PRECREDITSCHARA_0-3", "Flowey was right about one thing./")
ds_map_add(global.text_data, "KEY_PRECREDITSCHARA_0-4", "/RYou REALLY are an idiot./%%")