global.menu = 0
global.menucoord = 0
global.bmenucoord = 0
global.imenucoord = 0
global.menulength = 3
global.invc = 0
expect = 99 * 27364
talked = 0
if (global.deaths > 0)
	talked = 1
ismoving = false
timesacted = 0
depth = -9000
global.atk = 0
global.item[0] = 1
global.item[1] = 9999
global.item[2] = 3
global.item[3] = 3
global.fightpieces = 0
global.itempieces = 0
timesloved = 0